{% set name = "frozenlist" %}
{% set version = "1.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/frozenlist-{{ version }}.tar.gz
  sha256: 58bcc55721e8a90b88332d6cd441261ebb22342e238296bb330968952fbb3a6a

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - frozenlist
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aio-libs/frozenlist
  summary: A list-like structure which implements collections.abc.MutableSequence
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
